import Head from 'next/head'
import styles from '../styles/BlogCard.module.css';
import { GraphQLClient, gql } from 'graphql-request';
import BlogCard from '../components/BlogCard';
import Nav from '@/components/Nav';

const graphcms = new GraphQLClient(
  "https://api-ca-central-1.hygraph.com/v2/cldc5swc10x3w01urdgbx8mo7/master"
);

const QUERY = gql`
  {
    posts{
      id,
      title,
      datePublished,
      slug,
      content{
        html
      }
      author{
        name
        avatar{
          url
        }
      }
      coverPhoto{
        url
      }
    }
  }
`;

export async function getStaticProps(){
  const { posts } = await graphcms.request(QUERY);
  return{
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className="flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <div className="sm:mt-5 mt-10">
        <main className={styles.main}>
          {posts.map((post) => (
            <BlogCard 
              title={post.title} 
              author={post.author} 
              coverPhoto={post.coverPhoto} 
              key={post.id} 
              datePublished={post.datePublished} 
              slug={post.slug} 
            />
          ))}
        </main>
      </div>
    </div>
  )
}
